### ISSUE TITLE
Update Code of Conduct to match maintainers

### ISSUE THREAD

**Issue by RiRa12621** [bwplotka/configuration#10]
Code of conduct mentions the thanos maintainers and to contact them in the thanos slack for enforcing the code of conduct.
This should be adjusted to probably match this projects maintainers and add a proper way of contacting them

**Comment by bwplotka** [comment]
Good point, copy-pasta

**Comment by RiRa12621** [comment]
@bwplotka i think this is still like that, if you can point out the correct folks instead, i'm happy to create a PR for this

**Comment by bwplotka** [comment]
<3 

This might be the up-to-date list: https://github.com/orgs/configuration-fyi/people

**Comment by bwplotka** [comment]
Not sure if it's shared so: 
![image](https://user-images.githubusercontent.com/6950331/93449489-b8765100-f8cc-11ea-8b04-b595935319d3.png)
