### ISSUE TITLE
Icons are only displayed as black dots on Firefox

### ISSUE THREAD

**Issue by RiRa12621** [bwplotka/configuration#8]
## What did you expect to see?
Image taken with Google Chrome
![Screenshot 2020-04-23 at 11 53 33](https://user-images.githubusercontent.com/14996407/80085842-19397180-8559-11ea-8d8b-ad089dbef3e0.png)

## What are you seeing?
![Screenshot 2020-04-23 at 11 52 42](https://user-images.githubusercontent.com/14996407/80085860-235b7000-8559-11ea-9812-05875fc8ed81.png)

## Environment
Firefox 68.5.0esr (64-bit) 
on Mac OS 10.15.4 (19E266)

**Comment by bwplotka** [comment]
![](https://media1.giphy.com/media/13FrpeVH09Zrb2/giphy.gif)

Help wanted (:
